version: "3"

services:
  micro_codeflix_app:
    container_name: micro_codeflix_app
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
    #templates folder exists inside container only -- look at ./.docker/app/Dockerfile
    entrypoint: dockerize -wait tcp://micro_codeflix_db:3306 -timeout 40s /entrypoint.sh
    volumes:
      - ./www:/var/www
    ports:
      - 9000:9000
    networks:
      - micro-codeflix-net
    depends_on:
      - micro_codeflix_db
      - micro_codeflix_redis

  micro_codeflix_nginx:
    build: .docker/nginx
    container_name: micro_codeflix_nginx
    restart: always
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www
    networks:
      - micro-codeflix-net
    depends_on:
      - micro_codeflix_app

  micro_codeflix_db:
    build: .docker/mysql
    container_name: micro_codeflix_db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 33060:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - micro-codeflix-net

  micro_codeflix_redis:
    image: redis:alpine
    container_name: micro_codeflix_redis
    expose:
      - 6379
    networks:
      - micro-codeflix-net

networks:
  micro-codeflix-net:
    driver: bridge
